version: "3.1"

services:
  mongo:
    image: mongo:5.0.16
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=clean-node-api
    ports:
      - 27017:27017
