version: "3.1"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.16
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=clean-node-api
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm debug
    volumes:
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
