version: '3.1'

services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.16
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=clean-node-api
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    command: bash -c "npm install --omit=dev && npm run debug"
    restart: always
    volumes:
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./dist/:/usr/src/clean-node-api/dist/
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/clean-node-api?authSource=admin
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
